name: Path Trigger Workflow
on:
  push:
    branches:
      - main       # mainブランチにPushされた時のみ対象
    paths:
      - 'src/**'   #  srcディレクトリ配下に変更があった時のみ起動する

jobs:
  path-job:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: srcディレクトリ内のファイル確認
        run: |
          echo "=== src/sample.txt の中身を出力します ==="
          cat src/sample.txt